import "~/styles/globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import { cn } from "@hipec/ui/lib/utils";
import { TooltipProvider } from "@hipec/ui/components/tooltip";
import { Toaster } from "@hipec/ui/components/sonner";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TooltipProvider>
        <body className={cn(poppins.className, poppins.variable)}>
          {children}
        </body>
      </TooltipProvider>
    </html>
  );
}
